### PR TITLE
Require ffmpeg 2.0

### PR DESCRIPTION
**Pull request by augustg**
This will check for ffmpeg 2.0 during configuration. I'm not sure exactly what version we require at the moment, but i do know that 0.5.2 (the previous requirement) is too old.
Recent versions of most distros now have at least version 2.7 of ffmpeg.

I've also fixed a couple mistakes in the pkgconfig code.

### CODE REVIEW

**Comment by spigwitmer** [comment]
the new ffmpeg backend was targeted for 3.0 but works with anything as early as 2.8

**Comment by augustg** [comment]
I have only verified that it works with 2.8 and that it doesnt work with 0.8. But have have not tested that it doesnt work with versions inbetween, have you?

**Comment by spigwitmer** [comment]
2.8 and 3.0 specifically were tested and approved. I didn't even bother with anything earlier than that.

**Comment by augustg** [comment]
Ok.
I didn't set the requirements higher than 2.0 because i figured there was a decent chance it would work with slightly lower versions than 2.8. And i'm now going to invest any time testing those versions. Instead I left the door open for anyone to try. If it builds, great. If not, not a big deal.

Do you think i should adjust the required versions anyway?

**Comment by spigwitmer** [comment]
I looked through the APIs for 2.0 - 2.6. I'll merge this because they're compatible, though if we start piling up bug reports from movie playback I'd be inclined to tighten up the versions needed.

**Pull request merged**
