### PR TITLE
Single MSVC (updated) Project with tomcrypt and io additions

### PR DESCRIPTION
**Pull request by chrispable**
Since I did not get any feedback on #99 I decided to go ahead and do this. Windows compilation is EASY now.

Addresses issues #25, #66 (closed but unaddressed) and #99 

Prereqs: Install the DX9 SDK.

Procedure:
Open the stepmania-net2010.sln in any version of visual studio (2010 and newer; only 2010, 2013 and 2015 tested) and with VERY minor changes, your good to go!

MSVC compiler selection:
By default the project is configured for msvc2015 with xp support. To change this, in the solution explorer, simply right click each of the 5 projects and under Configuration Properties -> General look for the option of "Platform Toolset" You can set this to any toolchain you have installed. (To save clicks, make sure you select the All configurations configuration option in the upper left of each project selected). If you need a platform that I haven't prebuilt the libs for, look in the extern folder and drop your compiled lib in there.

Note that MSVC 2013 has a bug, it required use of the /FS switch (Or you have to build the project twice), however, MSVC 2010 does NOT support this switch and the switch is ONLY NEEDED by MSVC 2013. If you run an older version of MSVC, for each project, open the properties and (To save clicks, make sure you select the All configurations configuration option in the upper left of each project selected) simply go to Configuration Properties -> C/C++ -> Command line and delete the /FS flag from each of the 5 projects.

Build Instructions:
*To build, right click on the solution and say "Clean". Then right click on OpenITG and select Rebuild.*
That's it!

TO TEST:
Linux Compilation - Tomcrypt/tommath was updated and shoved into the project for testing purposes, the two are sadly intertwined because it's such a deep dependency. I do not anticipate compilation problems on linux but the performance improvements are drastic with this update and well worth the look. I also moved some folders around but they should be specific to windows - to make dependent libs easier to manage. I cannot test Linux compiles so I'd appreciate if someone could.

XBOX Compilation:
I cannot source a copy of msvc++2003 to test the xbox project and update it. You should just need to point it at some new directories in the solution is all though if theres a problem.

### CODE REVIEW

**Comment by spigwitmer** [comment]
I still have to get through the rest of the commit.  thanks a ton for doing the dirty work on this one.

several things so far (not worth doing an inline review because msvc and 600+ changed sources):
 - the linux build won't compile because `ltm_desc` is undefined, which is found in headers/tomcrypt_math.h. I noticed that the RIJNDAEL/SHA512 definitions in tomcrypt_custom.h we added for ITG2's file format were missing in this PR and was wondering if they were pulled out intentionally or not, as it's also missing the LTM_DESC define needed for it to function with libtommath.
 - The source files and the header locations in tomcrypt.vcxproj were hardcoded with a D:\oitg\openitg\src prefix, though yanking that with some sed magic and prepending $(ProjectDir) in the headers got me a successful build.
 - src/verinfo.h is a generated artifact and shouldn't be checked in (and/or should be added to .gitignore)
 - Something I probably should've covered up front by not being late to #99, but regarding the libs/dlls: how exactly were these built for each of the projects (ffmpeg, vorbis, libpng)? I'm fine with keeping the binaries in the same place as the source to make builds easier (thoughts, @terabyte ?) as long as there's the means of reproducing them.

**Comment by RodentVienna** [comment]
this is more than anyone could have potentially asked for, and you seriously went through a lot for this commit. I am left to say **thank you sincerely**, after all that was said within this developent cycle. I do have a lot of testing environment at the moment, in case somebody wants to field-test compiles for XP, 7, 10,   vanilla dedi-boxor w/stock kernel/ITG2/PIUIO. I do not have a modern linux installation ready for testing. Somebody guide methrough the minimum effort to setup a modern inux, and compile OITG, and i can test this as well.

**Comment by chrispable** [comment]
@spigwitmer I actually think point 1 is related to point 2 and my changes in making this work were pointing actually to a working source directory. Msvc loves to just change the directories around and I thought I caught all those. Explains why it compiles got me! I'll diff my directories and see what's up. In addition, a lot of preprocessor stuff was put in the project properties which could explain a bit. I'll keep digging. Thanks so much for checking that.

For point 3, I thought so too but it's been a part of every msvc build and wasn't added so I assumed it was needed on some level. I'll add it to fit ignore.

Point 4, Most binaries have project files in the oitg drive file. I open them in each version in msvc, produce the lib, move it to the correct spot. Exception of ffmpeg which is detailed in the windows build readme which uses msys (which was a huge pita btw because it was pretty vague about which flavor of what, the fact ffmpeg needs a patch [known ffmpeg bug for msys], and then trying not to get my PC to do 64 bit builds for some reason). Ffmpeg for some reason luckily just links in with whatever runtime, so when it just worked I threw my hands on the air and exclaimed "if it ain't broke I'm not touching it!"

Will dig into the tommath and timcrypt stuff more today.

**Comment by chrispable** [comment]
Lets see if that works. I copied the defines from the MSVC project into the custom and left both new and legacy defines in there just in case.

(/FS flag removed since I put the default at msvc 2015 this time around)

**Comment by harleyknd1** [comment]
RC1015, Cannot open include file afxres.h on my copy of visual studio 2015...
There's too much stuff here for me to even remotely keep track of what's what so idk how it should be tackled.

**Comment by chrispable** [comment]
@harleyknd1
https://community.developers.thomsonreuters.com/questions/8225/fatal-error-rc1015-cannot-open-include-file-afxres.html

Visual studio 2015 does not come with all features needed by default. You wouldn't be able to compile this without this PR anyway. Follow those directions to install the needed features.

**Comment by harleyknd1** [comment]
Right, 2 steps forward, 1 step back, fixed my nmake issue and installed the features... next problem:
The build completes successfully, but no "OpenITG-debug.exe" appears, I AM seeing a .vdi in my Program folder... but the .exe is nowhere to be found...

**Comment by chrispable** [comment]
This isn't possible to debug without a compilation log. Please post one to http://paste.jvnv.net or pastebin because they are very large

**Comment by harleyknd1** [comment]
https://paste.jvnv.net/view/lE91r

**Comment by chrispable** [comment]
According to this msvc was successful. The binary is at

C:\Users\Kirito\Downloads\openitg-vs-master-file\Program/OpenITG-debug.exe

If it's not check the source folder. If still not, check your antimalware software. This isn't a problem with this pr.

**Comment by harleyknd1** [comment]
http://imgur.com/a/7DwsS

Bitdefender flags the exe, as well as verinc.exe as infected.... any reason its tripping AV flags?

**Comment by chrispable** [comment]
No idea. This is a bitdefender problem. If you want you can send it to virustotal. Try compiling with release-sse2 in case the debug hooks kill it. You wouldn't want to play with a debug executable anyway

**Comment by harleyknd1** [comment]
https://www.virustotal.com/en/file/d60de87b6a669cbb52c93fd8ee4b4e06453b75e1afc34ae06def4ccd07165d5d/analysis/1492708172/

Building sse2 atm to see if that trips flags as well

**Comment by chrispable** [comment]
@spigwitmer I tested compilation using the docker system for Linux. Seems to work just fine BUT obviously fails to package because the version doesn't start with a number. I will let you verify however.

@harleyknd1 this is a GENERATED file by msvc, it's intentionally ignored in the source files and not committed. Did you follow the instructions to clean the project first? I'm not sure which process generates it but it is literally 3 lines, updated every build. The contents of my latest are:
```
unsigned long VersionNumber = 6;
extern const char *const VersionTime = "Wed Apr 19 08:34:39 2017";
extern const char *const VersionDate = "20170419";
```

**Comment by harleyknd1** [comment]
Yes, before each test build I even delete the files, right click project -> clean, followed by openitg right click -> rebuild.

**Comment by chrispable** [comment]
Sounds like your antimalware ate verinc.exe

Nothing I can do about that. If you trust the files just disable your protection. Or look into something better. You likely need to decline at this point.

**Comment by harleyknd1** [comment]
Welp, figured out the issue,
because verinc was spitting out stuff in a protected zone, bitdefender decided to nuke it, ended up manually scanning it and allowing it which makes oITG build properly. oITG builds that (for one reason or another) can't use verinc will be flagged as infected because well, no verification applied to them....

Now the next step is avcodec-57.dll, which as far as I'm aware is part of ffmpeg so I'm just going to use the shared libraries (note for others, use the 32bit libs, the 64 ones give a 0xc000007b error)

**Comment by chrispable** [comment]
Once again, not an issue with this pr. If you look at the documentation (granted it's fragmented, but for Windows it has always been this way), 

https://github.com/openitg/openitg/blob/master/README-Windows-build.md

4. to build the installer, from cmd or powershell

    assets\win32-installer\setup-installer-dir.bat


This will create the installer directory layout in inst-temp. You need to run the game from that directory layout, the build environment is NOT the play environment. You don't need to actually make the installer, just the directory layout.

**Comment by chrispable** [comment]
Hi, curious if theres any up date on this? It's been a little while.

**Comment by spigwitmer** [comment]
Thanks, I'd be good to merge this, however:

> the fact ffmpeg needs a patch [known ffmpeg bug for msys]
i'm concerned about that, as i don't remember having to patch anything to get ffmpeg working on a win10 build. which patch are you referring to?

**Comment by chrispable** [comment]
From #66 ffmpeg incorrectly detects fast_clz. Other projects have to build around it too. It took me a LONG time to track this down because you guys were using prebuilt ffmpeg prior to this.

See:
https://bugs.chromium.org/p/chromium/issues/detail?id=612288


Description of the bug:
https://chromium.googlesource.com/chromium/third_party/ffmpeg.git/+/53c64939ac73d14473f6ab3bb3119048512e3c01

**Comment by spigwitmer** [comment]
Merging anyway if that only affects builds and we have pre-builts. Thanks again for putting this together.

**Comment by sillybear** [comment]
@chrispable 
I followed the steps above and successfully compiled a build using MSVC 2013. I used 2013 w/ xp platform toolset for all 5 projects. However, when I opened the exe, I got errors and said it was missing avformat-57.dll, avcodec-57.dll, avutil-55.dll and swscale-4.dll. What's the fix for these?

**Comment by chrispable** [comment]
Those are part of ffmpeg. You need to follow the ffmpeg instructions and
copy the compiled dlls to the same folder as the exe. The Ffmpeg oitg
expects to use cannot be compiled with msvc hence why there's special
instructions and always have been. It has nothing to do with msvc.

Because it's complicated, these files are usually premade in the extern
folder.
https://github.com/openitg/openitg/tree/master/extern/ffmpeg-build/bin

**Comment by sillybear** [comment]
I see. Thanks for the link.

**Pull request merged**
