### PR TITLE
update ffmpeg driver for home builds

### PR DESCRIPTION
**Pull request by spigwitmer**
it's been awhile. a long while. apologies for that.

this series of commits modernizes openitg-home's dependency on ffmpeg to 3.0 as an attempt to pull myself out of the 32-bit era while debugging, but keeping the old way of doing things around for the arcade build at 0.4.9.

if the code looks good, my other request is a thumbs-up from someone else with a ubuntu installation laying around for being able to compile/run it as well before it's merged.

TODOs:
 * using 16-bit movie color depth results in an inconsistently reproducible bug involving a black screen. oh ffmpeg
 * uhh the win32 build. unfortunately I don't run windows. I don't know if vyhd does, and sure as hell terabyte doesn't. if someone has the knowhow (and patience) to freshen up the visual studio projects that'd be greatly appreciated.

### CODE REVIEW

**Comment by augustg** [comment]
I dont have ubuntu available, but I've tested on Debian 8.4 i386 with ffmpeg 2.8.6.

I've tested two configurations:
1. ./configure --enable-itg-arcade
2. ./configure

The arcade build worked out-of-the-box, just like before.
The second option with shared ffmpeg libs failed with error:
> arch/MovieTexture/FFMpeg_Helper.cpp: In function ‘CString averr_ssprintf(int, const char*, ...)’:
> arch/MovieTexture/FFMpeg_Helper.cpp:73:2: error: ‘av_make_error_string’ is not a member of ‘avcodec’
>   avcodec::av_make_error_string(szError, 1024, err);

I fixed it locally by replacing:
`avcodec::av_make_error_string(szError, 1024, err);`
with
`avcodec::av_strerror(err, szError, 1024);`

Looking at this documentation: http://www.ffmpeg.org/doxygen/3.0/group__lavu__error.html#ga1eb28ee6abc94ec8210a8cb721d792b8
av_make_error_string is static and not called by anything other than av_strerror. I'm curious as to how it compiles on your box? And which one is correct?

**Comment by spigwitmer** [comment]
i downloaded and extracted the debian package and it looks like they deliberately pull out the declaration of av_make_error_string from `error.h`, unlike with archlinux which just keeps that header in tact (the `static` keyword is clearly there. oops.).

**Comment by augustg** [comment]
Great! No more compile errors over here.

**Comment by spigwitmer** [comment]
ubuntu 16.04 likes it too at ffmpeg 2.8, merging

**Pull request merged**
